spring.application.name=Biglots


server.port=8082

spring.datasource.url=jdbc:mysql://localhost:3306/Biglots_store
spring.datasource.username=root
spring.datasource.password=Root

spring.jpa.hibernate.ddl-auto=update
