spring.application.name=Biglots


server.port=8082

spring.datasource.url=jdbc:mysql://localhost:3306/Biglots_store
spring.datasource.username=root
spring.datasource.password=Root

spring.jpa.hibernate.ddl-auto=update

## mail properties ==
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME:rakeshchindem.12@gmail.com}
spring.mail.password=${MAIL_PASSWORD:poqggefmctlunihb}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
